# ===================================
#  List Behavior Config
# ===================================

# Model List Column configuration
list: $/jaxwilko/mediastream/models/mediameta/columns.yaml

# Model Class name
modelClass: JaxWilko\MediaStream\Models\MediaMeta

# List Title
title: Media Meta Data

# Link URL for each record
recordUrl: jaxwilko/mediastream/metadata/update/:id

# Message to display if the list is empty
noRecordsMessage: No metadata found

# Records to display per page
recordsPerPage: 20

# Displays the list column set up button
showSetup: true

# Displays the sorting link on each column
showSorting: true

# Toolbar widget configuration
toolbar:
    # Partial for toolbar buttons
    buttons: list_toolbar

    # Search widget configuration
    search:
        prompt: backend::lang.list.search_prompt
